# Generated by Django 6.0.6 on 2026-09-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_activityrecord_croprecommendationrecord_diseasescan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseasescan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='disease_scans/'),
        ),
        migrations.AddField(
            model_name='diseasescan',
            name='is_development',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='diseasescan',
            name='model_version',
            field=models.CharField(default='baseline_resnet18', max_length=50),
        ),
        migrations.AlterField(
            model_name='diseasescan',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
