# Generated by Django 6.0.6 on 2026-09-14 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_diseasescan_image_diseasescan_is_development_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='croprecommendationrecord',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='croprecommendationrecord',
            name='farm_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.farmprofile'),
        ),
        migrations.AddField(
            model_name='croprecommendationrecord',
            name='recommendation_method',
            field=models.CharField(default='rule-based', max_length=50),
        ),
        migrations.AddField(
            model_name='croprecommendationrecord',
            name='weather_source',
            field=models.CharField(default='manual', max_length=50),
        ),
    ]
