# Generated by Django 6.0.6 on 2026-09-14 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_croprecommendationrecord_explanation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='irrigationassessment',
            name='crop',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='irrigationassessment',
            name='farm_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.farmprofile'),
        ),
        migrations.AddField(
            model_name='irrigationassessment',
            name='field_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='irrigationassessment',
            name='growth_stage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='irrigationassessment',
            name='input_sources',
            field=models.CharField(default='manual', max_length=100),
        ),
        migrations.AddField(
            model_name='irrigationassessment',
            name='irrigation_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='irrigationassessment',
            name='reasoning',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='irrigationassessment',
            name='rule_version',
            field=models.CharField(default='v1.0', max_length=50),
        ),
    ]
