# Generated by Django 6.0.6 on 2026-09-14 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_irrigationassessment_crop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldguardassessment',
            name='crop',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fieldguardassessment',
            name='disease_scan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.diseasescan'),
        ),
        migrations.AddField(
            model_name='fieldguardassessment',
            name='factors',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='fieldguardassessment',
            name='farm_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.farmprofile'),
        ),
        migrations.AddField(
            model_name='fieldguardassessment',
            name='growth_stage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fieldguardassessment',
            name='humidity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldguardassessment',
            name='preventive_actions',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='fieldguardassessment',
            name='rainfall',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldguardassessment',
            name='rule_version',
            field=models.CharField(default='v1.0', max_length=50),
        ),
        migrations.AddField(
            model_name='fieldguardassessment',
            name='soil_moisture',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldguardassessment',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldguardassessment',
            name='weather_source',
            field=models.CharField(default='manual', max_length=50),
        ),
    ]
