# Generated by Django 6.0.6 on 2026-09-14 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_fieldguardassessment_crop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sustainabilityassessment',
            name='calculation_method',
            field=models.CharField(default='rule-based', max_length=100),
        ),
        migrations.AddField(
            model_name='sustainabilityassessment',
            name='cost_savings_estimate',
            field=models.CharField(default='unavailable', max_length=100),
        ),
        migrations.AddField(
            model_name='sustainabilityassessment',
            name='energy_savings_estimate',
            field=models.CharField(default='unavailable', max_length=100),
        ),
        migrations.AddField(
            model_name='sustainabilityassessment',
            name='farm_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.farmprofile'),
        ),
        migrations.AddField(
            model_name='sustainabilityassessment',
            name='improvement_suggestions',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='sustainabilityassessment',
            name='input_values',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='sustainabilityassessment',
            name='positive_factors',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='sustainabilityassessment',
            name='rule_version',
            field=models.CharField(default='v1.0', max_length=50),
        ),
        migrations.AddField(
            model_name='sustainabilityassessment',
            name='source_labels',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='sustainabilityassessment',
            name='water_savings_estimate',
            field=models.CharField(default='unavailable', max_length=100),
        ),
    ]
