# Generated by Django 6.0.6 on 2026-09-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseasescan',
            name='disease_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='diseasescan',
            name='plant_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='diseasescan',
            name='prediction_status',
            field=models.CharField(default='uncertain', max_length=50),
        ),
    ]
