CROP_KNOWLEDGE_BASE = {
    'Rice': {
        'name': 'Rice',
        'scientific_name': 'Oryza sativa',
        'soil_type': 'Clayey, Loamy',
        'ph_range': (5.5, 7.0),
        'temp_range': (20, 35),
        'rainfall_range': (100, 250),
        'water_req': 'High',
        'season': 'Kharif',
        'duration': '120-150 days',
        'nutrient_req': 'High Nitrogen, Medium Phosphorus, Low Potassium',
        'deficiency_risks': 'Nitrogen deficiency causes yellowing of older leaves.',
        'excess_risks': 'Excess Nitrogen makes plants susceptible to lodging and pests.',
        'advantages': 'High yield in waterlogged areas.',
        'limitations': 'Extremely water-intensive.',
        'sustainability': 'High methane emissions. Consider Alternate Wetting and Drying (AWD).',
        'image_url': 'https://images.unsplash.com/photo-1595015243869-70335e390c58?auto=format&fit=crop&w=400&q=80',
        'reference': 'FAO Crop Water Information'
    },
    'Wheat': {
        'name': 'Wheat',
        'scientific_name': 'Triticum aestivum',
        'soil_type': 'Loamy, Clay Loam',
        'ph_range': (6.0, 7.5),
        'temp_range': (15, 25),
        'rainfall_range': (50, 100),
        'water_req': 'Moderate',
        'season': 'Rabi',
        'duration': '110-130 days',
        'nutrient_req': 'High Nitrogen, Moderate P & K',
        'deficiency_risks': 'Potassium deficiency leads to poor grain filling.',
        'excess_risks': 'N/A',
        'advantages': 'Staple food crop, highly mechanized.',
        'limitations': 'Sensitive to terminal heat stress.',
        'sustainability': 'Requires balanced NPK for long-term soil health.',
        'image_url': 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=400&q=80',
        'reference': 'FAO Crop Water Information'
    },
    'Maize': {
        'name': 'Maize',
        'scientific_name': 'Zea mays',
        'soil_type': 'Well-drained Loam',
        'ph_range': (5.8, 7.0),
        'temp_range': (18, 27),
        'rainfall_range': (60, 110),
        'water_req': 'Moderate',
        'season': 'Kharif / Zaid',
        'duration': '90-120 days',
        'nutrient_req': 'High N and K',
        'deficiency_risks': 'Phosphorus deficiency causes purple leaves.',
        'excess_risks': 'Sensitive to waterlogging.',
        'advantages': 'High yield potential, versatile uses.',
        'limitations': 'Highly sensitive to drought during tasseling.',
        'sustainability': 'Heavy feeder; requires crop rotation.',
        'image_url': 'https://images.unsplash.com/photo-1599818815197-29367d3448a3?auto=format&fit=crop&w=400&q=80',
        'reference': 'FAO Crop Water Information'
    },
    'Cotton': {
        'name': 'Cotton',
        'scientific_name': 'Gossypium',
        'soil_type': 'Black soil, Clayey',
        'ph_range': (5.8, 8.0),
        'temp_range': (25, 35),
        'rainfall_range': (40, 75),
        'water_req': 'Moderate to Low',
        'season': 'Kharif',
        'duration': '150-180 days',
        'nutrient_req': 'High N and K',
        'deficiency_risks': 'Magnesium deficiency causes red leaves.',
        'excess_risks': 'Excess Nitrogen promotes vegetative growth over bolls.',
        'advantages': 'High cash value.',
        'limitations': 'Highly susceptible to pests (bollworm).',
        'sustainability': 'Pesticide intensive. IPM strongly recommended.',
        'image_url': 'https://images.unsplash.com/photo-1596766465492-b43064fc600c?auto=format&fit=crop&w=400&q=80',
        'reference': 'FAO Crop Water Information'
    },
    'Millets': {
        'name': 'Millets',
        'scientific_name': 'Pennisetum glaucum / Sorghum bicolor',
        'soil_type': 'Sandy, Loamy (Tolerant to poor soils)',
        'ph_range': (5.5, 7.5),
        'temp_range': (25, 35),
        'rainfall_range': (30, 60),
        'water_req': 'Low',
        'season': 'Kharif',
        'duration': '70-100 days',
        'nutrient_req': 'Low',
        'deficiency_risks': 'Very hardy, minimal deficiency risks.',
        'excess_risks': 'Cannot tolerate waterlogging.',
        'advantages': 'Highly drought resistant and climate-resilient.',
        'limitations': 'Lower yield compared to major cereals.',
        'sustainability': 'Excellent for water conservation and soil restoration.',
        'image_url': 'https://images.unsplash.com/photo-1621245059632-4e4444569cb1?auto=format&fit=crop&w=400&q=80',
        'reference': 'FAO Crop Water Information'
    }
}
